### ISSUE TITLE
v0.12.1 depends on QCElemental <0.12

### ISSUE THREAD

**Issue by mattwelborn** [conda-forge/qcportal-feedstock#18]
Issue:
v0.12.1 depends on QCElemental <0.12. This results in qcportal v0.12.0 being installed by default in fresh environments. 

https://github.com/conda-forge/qcportal-feedstock/blob/721732c2993e017f54312ce8f3ffe89c9c6338e7/recipe/meta.yaml#L31<br/>

Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by bennybp** [comment]
This has been fixed at some point
