### ISSUE TITLE
QCPortal 0.14.0 did not deploy

### ISSUE THREAD

**Issue by mattwthompson** [conda-forge/qcportal-feedstock#25]
The most recent version online is 0.13.1 (https://anaconda.org/conda-forge/qcportal/files) which the client rejects the use of

Here's where I'm starting: https://github.com/conda-forge/qcportal-feedstock/runs/1194996059

**Comment by Lnaden** [comment]
So it looks like the failure here is because the server which QCPortal tried to connect to is on an unsupported version for this 0.14.0 client. I know @bennybp was working to upgrade the server. Once the server is up and stable, Portal here should be able to connect correctly and then this build will pass. Just need to wait for word from @bennybp

**Comment by Lnaden** [comment]
Sure, let me try

**Comment by mattwthompson** [comment]
I see a 0.14.0 already! https://anaconda.org/conda-forge/qcportal/files

So this should be good - I will close this once I can update locally, which I'd expect to happen soon (it's there, but I can't grab it locally, maybe something about how the cloud works that's over my head, but can fixed by waiting an hour and trying again)

**Comment by Lnaden** [comment]
It looks like a version of 0.14.0 is up on Anaconda Cloud now. However, I'm not sure if it will be stable it is given the uploader is `cf-staging` and not `conda-forge`. I'll keep an eye on it, we may have to do with #26, or some variant of it.

**Comment by mattwthompson** [comment]
It's possible my goof stepped on some toes, but I think the switch to `cf-staging` is intentional and happened some months ago:

https://anaconda.org/conda-forge/qcfractal/files
https://anaconda.org/conda-forge/numpy/files

**Comment by Lnaden** [comment]
Good to know about the staging. Fortunately, most any goof or slip up is easily resolved by bumping the build number.

**Comment by mattwthompson** [comment]
I'm able to update to 0.14.0 locally and tests now pass locally and on CI. Looks like it's resolved from our end, feel free to close if things are working well for you and other users
